#!/bin/dash

#Copyright (c) 2014 Luigi Tarenga <luigi.tarenga@gmail.com>
#Distributed under the terms of a MIT license.

export sshopt="-q -o ConnectTimeout=1 -o StrictHostKeyChecking=no"
cd $(dirname $0)

read server_role      < temp/server_role
read hostname         < temp/hostname
read current_leader   < temp/current_leader
read client_timeout   < conf/client_timeout
read cluster_nodes    < conf/cluster_nodes

if ! flock -e -w 0 temp/master_lock true ; then
   if [ "$server_role" = "leader" ] ; then
      case "$1" in
      if|set|unset)
         if [ -z "$2" ] ; then
            echo missing argument
            exit 1
         fi
         flock -e temp/activity_lock internals/client "$@"
      ;;
      noop)
         flock -e temp/activity_lock internals/client "$@"
      ;;
      get)
         flock -s temp/activity_lock internals/client get "$2"
      ;;
      status)
         echo "Leader:  $hostname"
         for h in $cluster_nodes ; do
            [ "$h" = "$hostname" ] && continue
            read follower_timeout < temp/${h}_follower_timeout
            if [ "$follower_timeout" -gt 0 ] ; then
               echo Follower: $h
            else
               echo Unknown: $h
            fi
         done
      ;;
      add-member|del-member)
         if [ -z "$2" ] ; then
            echo missing argument
            exit 1
         fi
         read cluster_nodes < conf/cluster_nodes
         cluster_nodes_new="$cluster_nodes $2"
         if [ "$1" = "del-member" ] ; then
            cluster_nodes_new=$(for h in $cluster_nodes; do [ "$h" != "$2" ] && echo -n "$h "; done)
         fi
         [ "$1" = "add-member" ] && ssh $sshopt $2 $PWD/lite-raft first-boot
         echo inserting conf_old_new.
         if flock -e temp/activity_lock internals/client conf_old_new "$cluster_nodes_new" ; then
            echo conf_old_new committed.
            echo inserting conf_new.
            if flock -e temp/activity_lock internals/client conf_new ; then
               echo conf_new committed.
               [ "$1" = "del-member" ] && ssh $sshopt $2 $PWD/lite-raft stop
            else
               echo returned error $?
            fi
         else
            echo returned error $?
         fi
      ;;
      esac

   elif [ -n "$current_leader" ] ; then
      ssh $sshopt "$current_leader" $PWD/$0 "$@"
   else
      echo leader is not yet ready
      exit 1
   fi
else
   #no process running here, return error
   echo no server running on $hostname. cannot process request.
   exit 1
fi
