#!/bin/dash

#Copyright (c) 2014 Luigi Tarenga <luigi.tarenga@gmail.com>
#Distributed under the terms of a MIT license.

export sshopt="-o ControlPath=~/.ssh/lite-raft-socket-%h -o ControlMaster=auto \
-o ConnectTimeout=1 -o ServerAliveInterval=2 -o ServerAliveCountMax=3 \
-o PasswordAuthentication=no -o StrictHostKeyChecking=no -q"

#this makes binaries a little faster on linux
export LANG=C

if [ $# -ne 0 ] ; then
   echo "Usage: ${0##*/}"
   echo "  This is the main server of lite-raft. Usually it's started"
   echo "  with \"lite-raft start\" command."
   exit 0
fi

cd $(dirname $0)

if [ -d /dev/shm ] ; then
   mkdir -p /dev/shm/lite-raft/temp
   ln -sf /dev/shm/lite-raft/temp temp
else
   mkdir -p temp
fi

#hostname -s is not supported on HP-UX
hostname=$(hostname)
hostname=${hostname%%.*}

trap 'rmdir temp/master_lockdir; exit 0' HUP INT TERM
if ! mkdir temp/master_lockdir 2> /dev/null ; then
   echo "cannot create lockdir. check if another lite-raft-server is running."
   exit 1
fi

while true ; do
   read cluster_nodes < conf/cluster_nodes
   for h in $cluster_nodes ; do
      if [ "$h" != "$hostname" ] ; then
         [ -S ~/.ssh/lite-raft-socket-$h ] || ssh -MNf $sshopt $h
      fi
   done
   sleep 4
done &

echo ""       > temp/current_leader
echo follower > temp/server_role
echo 0        > temp/commit_index
echo false    > temp/quorum_heartbeat
cp conf/election_timeout temp/election_timeout

if [ -f state-machine-snapshot/cur/last_included_index ] ; then
   cp state-machine-snapshot/cur/last_included_index temp/last_log_applied
else
   echo 0 > temp/last_log_applied
fi

echo $hostname > temp/hostname
read cluster_nodes < conf/cluster_nodes
read snapshot_period < conf/snapshot_period

echo "$(date) starting as follower."
while true ; do
   read server_role < temp/server_role
   sleep 1 & sleep_pid=$!
   case "$server_role" in 
    follower)
      lock_timeout=10 internals/follower
    ;;
    candidate)
      #sleep between 0 and 0.999600 seconds. 
      delay=$(od -An -N1 -tu1 /dev/urandom)
      #on some OS leading 0 can trigger octal syntax error (like 069)
      delay=0.$(((${delay##*[ 0]0}+0)*3920))
      #where sleep doesn't support decimal fallback to perl sleep.
      sleep $delay 2> /dev/null || utils/sleep.pl $delay
      lock_timeout=10 internals/candidate
    ;;
    leader)
      lock_timeout=10 internals/leader
    ;;
   esac

   first_log_index=0
   if [ -f state-machine-snapshot/cur/last_included_index ] ; then
      read first_log_index < state-machine-snapshot/cur/last_included_index
   fi
   read last_log_index < state/last_log_index
   if [ $(($last_log_index-$first_log_index)) -gt $snapshot_period ] ; then
      lock_timeout=10 internals/create-snapshot
   fi

   wait $sleep_pid
done
