#!/bin/dash

#Copyright (c) 2014 Luigi Tarenga <luigi.tarenga@gmail.com>
#Distributed under the terms of a MIT license.

#this script implement an exclusive lock. using flock is faster but less
#portable. OpenBSD and HP-UX don't have a flock binary by default.

quit () {
   mv temp/activity_lockdir_ex temp/activity_lockdir_un
   exit $1
}

trap 'quit 0' HUP INT TERM

until mv temp/activity_lockdir_un temp/activity_lockdir_ex 2> /dev/null ; do
   if [ -n "$lock_timeout" ] ; then
      lock_timeout=$(($lock_timeout-1))
      [ "$lock_timeout" -lt 0 ] && exit 1
   fi

   #on HP-UX decimal seconds is not supported. use the perl implementation
   sleep 0.1 2> /dev/null || utils/sleep.pl 0.1
done
