#!/bin/dash

#Copyright (c) 2014 Luigi Tarenga <luigi.tarenga@gmail.com>
#Distributed under the terms of a MIT license.

read server_role < temp/server_role
read cluster_nodes < conf/cluster_nodes
read hostname < temp/hostname

valid_member="false"
for h in $cluster_nodes ; do
   [ "$h" = "$hostname" ] && valid_member="true"
done

if [ "$valid_member" = "false" ] ; then
   echo quitter > temp/server_role
   echo $(date) switching to quitter. not a member anymore.
fi
