#!/bin/dash

cd $(dirname $0)

case $1 in
 start)
   if [ -z "$2" ] ; then
      echo you need to specify a package name.
      exit 1
   fi 

   if [ -d temp/monitor_lockdir_"$2" ] ; then
      echo monitor lockdir already exist. cannot start pkg-mon.
      exit 1
   fi 
   ./pkg-mon $2 > message-log/pkg-mon.$2.log &
 ;;

 stop)
   printf "sending TERM signal and waiting for package to halt."
   shell_cmd=$(head -1 pkg-mon)
   shell_cmd=${shell_cmd#\#!}
   pkill -x -f "$shell_cmd ./pkg-mon $2"
   while pkill -0 -x -f "$shell_cmd ./pkg-mon $2" ; do
      sleep 1
      printf .
   done
   fuser -s -k -TERM ~/.ssh/lite-raft-socket-* 2>/dev/null
   echo " done."
 ;;

 init)
   timeout=$(control-scripts/$2 echo timeout)
   preferred_owner=$(control-scripts/$2 echo preferred_owner)
   ./lite-raft-remote set packages/$2/timeout ${timeout:-60}
   ./lite-raft-remote set packages/$2/owner "$preferred_owner"
   ./lite-raft-remote set packages/$2/state unknown
   ./lite-raft-remote set packages/$2/tick 0
 ;;

 status)
   #echo -n is not supported on hp-ux
   printf "package owner: " ; ./lite-raft-remote get packages/$2/owner
   printf "package state: " ; ./lite-raft-remote get packages/$2/state
   printf "package tick:  " ; ./lite-raft-remote get packages/$2/tick
 ;;

 *)
   echo "Usage: ${0##*/} { init | start | stop | status }"
   echo "  Main script to init, start or stop the package monitor service."
esac
